Remove '?' from the filename (Unsupported on windows)
I just cloned this repository and when I checked inside, I found the folder to be empty.
The reason was this following error :
error: invalid path 'competitive-programming/HackerRank/Python/What's Your Name?.py'

This is because Windows doesn't support question mark within the file/directory names. Fixing it can encourage the other learners using windows, to contribute to this repository